Add country distances to transports api
Contargo/iris pull request #65
Opened 2022-11-02 17:12 UTC by greenhalos

2022-11-03 07:55 UTC, Theiaz commented
Tested with Straßbourg. Overall distance for outward way is 87km, sum of distances by country is 88km. 
Seems like rounding errors needs to be fixed (like you said).

request:
```json
{
  "transportChain": [
    {
      "from": {
        "type": "TERMINAL",
        "uuid": "1300000000000025"
      },
      "to": {
        "type": "ADDRESS",
        "lat": 48.573086,
        "lon": 7.705879
      },
      "modeOfTransport": "ROAD",
      "loadingState": "EMPTY"
    },
    {
      "from": {
        "type": "ADDRESS",
        "lat": 48.573086,
        "lon": 7.705879
      },
      "to": {
        "type": "TERMINAL",
        "uuid": "1300000000000025"
      },
      "modeOfTransport": "ROAD",
      "loadingState": "FULL"
    },
    {
      "from": {
        "type": "TERMINAL",
        "uuid": "1300000000000025"
      },
      "to": {
        "type": "SEAPORT",
        "uuid": "1300000000000006"
      },
      "modeOfTransport": "WATER",
      "loadingState": "FULL"
    }
  ]
}

```

2022-11-03 07:56 UTC, Theiaz requested changes

2022-11-03 07:56 UTC, Theiaz commented on src/main/java/net/contargo/iris/routing/RoutingQueryResult.java
> +        this.countryDistances = countryDistances;
I would prefer naming like `distancesByCountry`

2022-11-03 07:57 UTC, Theiaz approved these changes

2022-11-08 07:41 UTC, Theiaz approved these changes

2022-11-08 07:41 UTC, Theiaz commented on src/main/java/net/contargo/iris/route/service/RouteDataRevisionPartEnricher.java
> +    private Map<String, BigDecimal> adjust(Map<String, BigDecimal> distancesByCountry, BigDecimal finalDistance) {
`finalDistance` -> `totalOnewayDistance`

2022-11-08 07:41 UTC, Theiaz commented on src/main/java/net/contargo/iris/route/service/RouteDataRevisionPartEnricher.java
> +                        return e.getValue();
Why is this necessary (comment or better method name?)

2022-11-08 07:41 UTC, Theiaz commented on src/main/java/net/contargo/iris/route/service/TruckRoutingPartEnricher.java
> +    private Map<String, BigDecimal> extractDistancesByCountry(BigDecimal finalDistance, TruckRoute truckRoute) {
This is nearly the same code like in `RouteDataRevisionPartEnricher` except the arguments differ (could be the same unwrapping distanceService.getDistancesByCountry) and calculation of the new distance is implemented in two different ways.

Would be better to use the same method inside a class which name describes the usecase of this adjustment.

2022-11-08 08:16 UTC, bjoernmartin commented on src/main/java/net/contargo/iris/routedatarevision/api/RouteDataRevisionApiController.java
> +                    getLocale()), "routerevision.countryDistances.missmatch", BAD_REQUEST);
```suggestion
            throw new RestApiException(messageSource.getMessage("routerevision.countryDistances.mismatch", null,
                    getLocale()), "routerevision.countryDistances.mismatch", BAD_REQUEST);
```
I couldn't find the property file where this key is specified. Is it missing?

2022-11-08 08:16 UTC, bjoernmartin commented on src/main/java/net/contargo/iris/routing/osrm/Osrm5Response.java
> +            + ", distancesByCountry=" + distancesByCountry + '}';
Was it intentional to drop the geometries here?

2022-11-08 08:16 UTC, bjoernmartin commented on src/main/java/net/contargo/iris/routedatarevision/DistancesByCountryUtil.java
> +        return result;
In addition, in my understanding the code in `TransportDescriptionRoadExtender#alignDistancesByCountry(..)` assumes that we cover all countries since we perform adjustments if the sum of distances per country does not match the total. So missing countries would skew that result, wouldn't it?

2022-11-08 19:25 UTC, greenhalos commented on src/main/java/net/contargo/iris/routing/osrm/Osrm5Response.java
> +            + ", distancesByCountry=" + distancesByCountry + '}';
Yes, geometries are rubbish to print in a toString() Method, they just blow up logs ;)

2022-11-08 19:47 UTC, greenhalos commented on src/main/java/net/contargo/iris/routedatarevision/api/RouteDataRevisionApiController.java
> +                    getLocale()), "routerevision.countryDistances.missmatch", BAD_REQUEST);
It was there, but was removed by mistake, now it is back again.

2022-11-08 19:53 UTC, greenhalos commented on src/main/java/net/contargo/iris/route/service/TruckRoutingPartEnricher.java
> +    private Map<String, BigDecimal> extractDistancesByCountry(BigDecimal finalDistance, TruckRoute truckRoute) {
It is not in the RouteDataRevisionPartEnricher anymore. Similar methods reside in TruckRoutingPartEnricher and TransportDescriptionRoadExtender. They look similar, but are different, the one works with with `TransportResponseSegment` and `Integer` as distances and the other one works with `TruckRoute` and BigDecimal as distances. As they are both used for the different api endpoints and they just look similar but are different due to the different types, I decided that "duplication" is okay ;)

2022-11-08 20:00 UTC, greenhalos commented on src/main/java/net/contargo/iris/route/service/RouteDataRevisionPartEnricher.java
> +                        return e.getValue();
This code does not exist anymore

2022-11-08 21:38 UTC, greenhalos commented on src/main/java/net/contargo/iris/routedatarevision/DistancesByCountryUtil.java
> +        return result;
Now it uses the CountryCode enum.

2022-11-09 07:42 UTC, omessner approved these changes

2022-11-10 08:23 UTC, merged